# Generated by Django 6.0 on 2026-03-11 12:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='default', max_length=30)),
                ('email', models.EmailField(default='example@example.com', max_length=30)),
                ('book_name', models.CharField(max_length=30)),
                ('author_name', models.CharField(max_length=30)),
                ('book_category', models.CharField(max_length=15)),
                ('book_chapter', models.CharField(max_length=10)),
                ('book_pages', models.CharField(max_length=10)),
                ('book_img', models.ImageField(null=True, upload_to='uploadedFiles')),
                ('book_file', models.FileField(null=True, upload_to='documents')),
            ],
        ),
        migrations.CreateModel(
            name='type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.CharField(max_length=50)),
                ('user_name', models.CharField(max_length=30)),
                ('diy_name', models.CharField(max_length=50)),
                ('diy_type', models.CharField(max_length=7)),
                ('diy_material', models.CharField(max_length=500)),
                ('diy_img', models.ImageField(null=True, upload_to='uploadedFiles')),
            ],
        ),
        migrations.CreateModel(
            name='book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='default', max_length=30)),
                ('email', models.EmailField(default='example@example.com', max_length=30)),
                ('book_name', models.CharField(max_length=30)),
                ('author_name', models.CharField(max_length=30)),
                ('book_category', models.CharField(max_length=15)),
                ('book_chapter', models.CharField(max_length=10)),
                ('book_pages', models.CharField(max_length=10)),
                ('book_img', models.ImageField(null=True, upload_to='uploadedFiles')),
                ('book_file', models.FileField(null=True, upload_to='documents')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
