# Generated by Django 6.0 on 2026-03-13 19:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readingapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='books',
        ),
        migrations.AddField(
            model_name='book',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='author_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_category',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_chapter',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_file',
            field=models.FileField(blank=True, null=True, upload_to='documents'),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_img',
            field=models.ImageField(blank=True, null=True, upload_to='uploadedFiles'),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_pages',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='book',
            name='email',
            field=models.EmailField(default='example@example.com', max_length=50),
        ),
        migrations.AlterField(
            model_name='type',
            name='diy_img',
            field=models.ImageField(blank=True, null=True, upload_to='uploadedFiles'),
        ),
        migrations.AlterField(
            model_name='type',
            name='diy_type',
            field=models.CharField(max_length=20),
        ),
    ]
