# Generated by Django 6.0 on 2026-03-14 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readingapp', '0002_delete_books_book_created_at_alter_book_author_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='type',
        ),
        migrations.RemoveField(
            model_name='book',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='book',
            name='book_category',
            field=models.CharField(choices=[('Classic', 'Classic'), ('Mystery', 'Mystery'), ('Romantic', 'Romantic'), ('Spiritual', 'Spiritual'), ('Fiction', 'Fiction'), ('Adventure', 'Adventure')], max_length=20),
        ),
        migrations.AlterField(
            model_name='book',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='book',
            name='username',
            field=models.CharField(max_length=30),
        ),
    ]
