# Generated by Django 6.0 on 2026-03-16 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readingapp', '0003_delete_type_remove_book_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_agegroup',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
